### ISSUE TITLE
dnf-plugin-snapper/python3-dnf-plugin-snapper f41

### ISSUE THREAD

**Issue by muff11n** [rpm-software-management/dnf-plugins-extras#222]
hello, seems like the plugin installs correctly on fedora 41, but based on dnf --version output the plugin is not activated and doesn't automatically trigger snapshots, was looking into the logs found nothing, so puzzled how can I enable it (looked into the dnf plugins directory was set to 1)

do I have to do anything else to make it work ?

was also reading the docu here...

**Comment by pkratoch** [comment]
Hello, Fedora 41 switched to the dnf5 packages manager and the snapper plugins is not implemented for dnf5. When installing `python3-dnf-plugin-snapper`, the package `python3-dnf` is installed as a dependency, but when running dnf, dnf5 is used, so the snapper plugin doesn't have any effect, because it's a plugin for dnf4.

The missing snapper plugin for dnf5 is tracked in issue https://github.com/rpm-software-management/dnf5/issues/1700 , so I am closing this one as it's a duplicate.
